apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ii2bi3e6v-java-quarkus
  janus-idp.io/tekton: ii2bi3e6v-java-quarkus
  backstage.io/kubernetes-id: ii2bi3e6v-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ii2bi3e6v-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
